---
name: Sophie Breitbart
date: "`r format(Sys.time(), '%B %Y')`"
qualifications: BA, Biology
position: Data Scientist, Evolutionary Biologist, Ecologist
address: Toronto, Canada
email: sophie.breitbart@gmail.com
website: sbreitbart.github.io
github: sbreitbart
linkedin: sophiebreitbart
twitter: SophieBreitbart
headcolor: "414141"
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Education
```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "PhD in Ecology & Evolutionary Biology",
  "University of Toronto",
  "Toronto, Canada",
  "2018 - present",
    list("Thesis: Effects of Urbanization on the Evolutionary Ecology and Population Genetics of Common Milkweed",
         "Advisors: Drs. Marc Johnson and Helene Wagner"),

  "BA in Biology, Certificate in Integrative Genomics Sciences: Informatics and Modeling",
  "Wesleyan University",
  "Middletown, Connecticut",
  "2012 - 2016",
    list("Undergraduate researcher (2013-2016): Minnow biogeography and bacterial phylogeography")
  ) %>%
  detailed_entries(degree, dates, uni, loc, details)

```

# Experience
```{r consulting}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  
  "Data Scientist", "University of Toronto and University Health Network", "Toronto, Canada", "2023 - Present", 
  
    list("Cleaned, wrangled, and visualized Twitter data for ``\\#Team Vaccine: Exploring the History of Toronto’s COVID-19 Vaccination Initiative through Social Media\" project"),
  

  "Research Assistant", "University of Toronto", "Toronto, Canada", "2018 - Present", 
  
    list(
      # "Conducted research on how urbanization influences plant ecology and evolution",
         
         "Used linear mixed models and multivariate analyses to estimate the impacts of urbanization on reproductive success and genetic divergence in a native plant",
         
         "Quantified how urbanization shapes genetic diversity and population structure of a native plant",
         
         "Taught tutorials in data science, biostatistics, evolutionary biology, ecology, and molecular genetics"),
  
  
  "Staff Scientist I", "Princeton Hydro", "South Glastonbury, Connecticut", "2016 - 2018", 
  
  list("Designed detailed dam removal engineering plan sets with AutoCAD",
  
  "Analyzed geospatial data and generated maps using ArcGIS",
  
  "Assisted developing strategies for protecting water resources and co-authoring watershed management plans"),
  
    
  "Aquatics Intern", "Princeton Hydro", "South Glastonbury, Connecticut", "2016", 
  
  list("Assisted in lake and landfill water quality assessments",
  
  "Helped conduct biological surveys of fish and invasive plant communities in various lakes")
  
  ) %>% 
  
  detailed_entries(role, dates, company, loc, details)
```

# Selected Publications

Full list of publications [here.](https://scholar.google.com/citations?hl=en&user=vx2HzukAAAAJ&view_op=list_works&sortby=pubdate)

```{r}
bibliography_entries("publications.bib")
```



\newpage

# Funding & Awards
```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Zimmerman/Weis Graduate Award ($10,950)", "University of Toronto", "2021",
  "EEB PhD Research Grant ($2,000)", "University of Toronto", "2021",
  "Centre for Urban Environments Research Grant ($1,940)", "University of Toronto", "2021",
  "Zimmerman/Weis Graduate Award ($10,950)", "University of Toronto", "2020",
  "Grant in Aid of Research ($1,000)", "Sigma Xi", "2020",
  "Centre for Urban Environments Workshop/Symposium Grant ($2,500)", "University of Toronto", "2020",
  "CREATE Enviro Trainee ($23,700)", "NSERC", "2018",
  "College of the Environment Summer Research Fellowship ($4,000)", "Wesleyan University", "2014",
  "Carol and Robert Lynch Student Research Fund Grant ($905)", "Wesleyan University", "2013",
  "Howard Hughes Medical Institute Grant ($884)", "Wesleyan University", "2013",
  "Joseph Scacalossi Scholarship ($4,000)", "Public Employees Federation", "2012") %>%
  brief_entries(award, year, from) 

```

# Skills
```{r tutoring}
tribble(
  ~ title, ~ code, ~ campus, ~ skill, ~ purple,
  "Applied forecasting", "ETC3550/ETC5550", "Clayton", "Code", TRUE,
  "Communicating with Data", "ETC5523", "Clayton", "2021 S2", FALSE
) %>% 
  brief_entries(glue::glue("\\textbf{<code>}: <title> (Monash <campus>)", .open = "<", .close = ">"), skill, .protect = FALSE)


# Code: R, bash
# Bioinformatics: illumina whole genome assembly, alignment, and SNP calling with GATK, samtools.
# Computing: SLURM, git.
# Statistics: Linear models, mixed models, classical stats
# (t-tests, anovas, etc), genetic demographic modeling.
# Geospatial analysis & visualization: geospatial modeling in R (raster, sp, ggplot2).
# 
# 
# More than 5 years experience
# • R, Git, Bash, HTML, CSS, Python, SQL, ShinyApps
# • Machine learning
# • Predictive modelling and timeseries analysis
# • Data mining and visualization
# • Creating summary reports with RMarkdown notebooks
# • High-throughput computing
# • Reporting and presenting quantiative research

```

# Teaching experience

\newpage

## Industry Workshops

```{r workshops}
tribble(
  ~ role, ~ course, ~ organisation, ~ country, ~ dates, ~ details,
  "Teaching assistant", "Tidy Time Series and Forecasting in R", "rstudio::conf", "USA", "Jan. 2020", "Two day workshop with Rob Hyndman on forecasting using tidyverse workflows.",
  "Instructor", "Interactive documents with Shiny", "CSIRO", "Australia", "Nov. 2019", "Two day intermediate workshop on developing of shiny applications.",
  "Instructor", "Data Wrangling", "Monash University", "Australia", "Sep. 2019", "A short workshop in the 'R Workshops for Beginners' series on using tidyr and dplyr to wrangle data.",
  "Helper", "Tidyverse developer day", "RStudio", "France", "Jul. 2019", "A one day developer day where I helped R users resolve issues on tidyverse packages.",
  "Teaching assistant", "High-dimensional time series analysis", "ISI WSC", "Malaysia", "Aug. 2019", "One day short course with Rob Hyndman for analysing and forecasting large collections of time series.",
  "Instructor", "The grammar of animation", "Monash University", "Australia", "Mar. 2019", "A short workshop for NUMBAT group on creating animated graphics in R with the gganimate package.",
  "Teaching assistant", "Master R Developer Workshop", "RStudio", "Australia", "Dec. 2016", "A two day workshop with Hadley Wicham on programming with R and developing R packages.",
) %>% 
  brief_entries(glue::glue("\\textbf{<course>}: <role> (<organisation>, <country>) \\newline <details>", .open = "<", .close = ">"), paste0(dates, "\\newline"), .protect = FALSE)
```


# Research output
## Presentations

```{r talks}
tribble(
  ~ when, ~ title, ~ details, ~ where, ~ url,
  "2020", "Forecasting with multiple seasonality", "Methods and techniques to multiple seasonal forecasting in R", "UK NHS", "https://slides.mitchelloharawild.com/nhs2020/",
  "2020", "Probabilistic cross-temporal hierarchies", "Recent developments of temporal reconciliation in fable.", "ISF", "https://slides.mitchelloharawild.com/isf2020/"
) %>% 
  brief_entries(glue::glue("\\textbf{<title>}: <details> \\newline \\url{<url>}", .open = "<", .close = ">"), when, .protect = FALSE)
```


<!-- # Data analysis projects -->

<!-- # Relevant Skills -->
<!-- ```{r} -->
<!-- cvskill("Data Analysis", c("Visualisation", "Data Cleaning", "Forecasting", "Modelling", "Communication", "Inference", "Machine Learning", "Web Scraping")) -->
<!-- cvskill("Programming", c("R", "Python", "SQL", "Java", "C", "C++", "HTML/CSS", "TeX", "MATLAB")) -->
<!-- ``` -->

